Cargo.lock, src/lib.rs
Fixes #7 
These patches teach Tarpaulin to add the "-no-pie" flag where allowed and needed.
This has been tested on Ubuntu 17.04 (requires the linker flag) and Ubuntu 15.04 (rejects the linker flag).
=> Add "link-args=-no-pie" automatically where apropriate

src/main.rs
Clap will word wrap the help texts on a per-line basis. So the newline in the help text becomes significant in the output and you end up with this output on a standard 80-column terminal:
```
--ciserver <SERVICE>    Name of service, supported services are:
travis-ci, travis-pro, circle-ci, semaphore,
jenkins and codeship.
If you are interfacing with coveralls.io or
another site you can
also specify a name that they will recognise.
Refer to their documentation for this.
```
Notice how there is an unnecessary line break between `you can` and `also specify`. This is the newline from the help text that has been preserved in the output.
=> Remove extra newline in help text

src/lib.rs
With a `HashMap`, the output order is undefined. Instead, use a
`BTreeMap` and keep the output order stable.
=> output: sort output paths

src/config.rs, src/lib.rs, src/main.rs
This way tarpaulin will behave more consistently with the rest of the cargo subcommands.
The previously added default to `--all` really broke my CI, as I have in my workspace a single package on which tarpaulin should be run : the others cannot be built by tarpaulin with their default feature flags require system libs that are not installed on travis (namely Mesa), forcing me to manually exclude all other packages like this:
https://github.com/Smithay/wayland-rs/blob/ecca2d54340da7afca7b364cb53da61935211de9/.travis.yml#L55
=> Add a --all flag to manually turn on building a whole workspace

src/ptrace_control.rs
Using `ptrace(PTRACE_GETEVENTMSG, ...)` doesn't work with nix v0.9.0.
=> Use ptrace_getevent

src/source_analysis.rs
Without this , lines containing only `)?;` were not ignored.
This removes around 150 lines detected as "uncovered" on wayland-rs.
=> Add ( and ) to the list of chars in ignored lines.

Dockerfile
This is the first part for #65.
You can see the image here: https://hub.docker.com/r/robinst/tarpaulin/
You can try it out in a repository where you want to calculate coverage using this command:
docker run --security-opt seccomp=unconfined -v "$PWD:/volume" robinst/tarpaulin
If you want more options, you have to run it like this:
docker run --security-opt seccomp=unconfined -v "$PWD:/volume" robinst/tarpaulin cargo tarpaulin --ignore-tests --out Xml
If you want to run multiple commands, you have to use a shell like this:
docker run --security-opt seccomp=unconfined -v "$PWD:/volume" robinst/tarpaulin sh -c "cargo build && cargo tarpaulin"
After merging this (or even before), you can set up an automated build in your account using "Create Automated Build" on Docker hub:
You will be able …
=> Add Dockerfile for building on Docker hub

README.md
Fixes #102.
The new [`runtime-macros`](https://crates.io/crates/runtime-macros) crate provides all the functionality needed to get Tarpaulin working with procedural macros. I've added a short section to the readme to point users to it.
=> Document possible use of `runtime-macros`

README.md, src/lib.rs
This isn't a production quality implementation, it's currently just a hack for my own personal use.  In particular, there are no tests for the new code, and the output format could use some improvement.  If you're interested in merging this feature in I would be happy to clean things up.
For reference, this is what the new output format looks like for the simple example project: 
```
Coverage Results
src/lib.rs: 6
src/unused.rs: 4-6
src/lib.rs: 5/6
src/unused.rs: 0/3
55.56% coverage, 5/9 lines covered
```
Fixes #92
=> Aggregate results

src/report/cobertura.rs
Change the XML output so that in the <class> objects, the filename attribute is a path relative to project root, rather than just the filename.
Without this codecov is unable to differentiate two files having the same filename but being in different directories, and just drops all files with this name.
Fixes #130
I tested this on my CI to ensure it does indeed solve the issue.
=> Use root-relative filepath in XML output

src/lib.rs
I noticed that files with no uncovered lines are still getting printed in the uncovered lines listing.  Thanks for the new release!
=> Don't print a line for files that have no uncovered lines

src/source_analysis.rs
This is an attempt at propagating upward unreachability in processed files. The rationale being that code that can be statically determined to be unreachable cannot be tested, and should not be marked as missed in coverage.
The algorithm for propagating coverage I implemented is the following:
- `unreachable!()` macro invocation is unreachable
- a list of statements is unreachable iff at least one of the statements is unreachable
- a loop is unreachable iff its body is unreachable
- an if block is unreachable iff both its branches are unreachable
- in particular an if with no else branch is *reachable*
- a match block is unreachable iff all its branches are unreachable
- in particular, a match with no branch is unreachable, as it must be matching on an uninhabited type like an empty enum …
=> Propagate unreachability in coverage

src/breakpoint.rs, src/ptrace_control.rs, src/report/cobertura.rs, src/report/coveralls.rs, src/report/mod.rs, src/source_analysis.rs, src/test_loader.rs, src/traces.rs
Found a lot of trailing spaces in code:
```sh
find src/ -name '*.rs' -exec grep -e ' $' {} \;
```
Cleaned up with regex.
P.S. I have not touched the data files, but there are 3 files with the same issue.
=> Cleanup trailing spaces

src/config/mod.rs, src/lib.rs, src/main.rs
While additional features could already be specified, this adds the
ability to disable default features. Related to #25.
=> Add an option for no default features in target build

Dockerfile, Dockerfile-nightly
* enable procmacro2_semver_exempt for stable like for experimental
* fix cargo install for Rust 2018 edition applications
* enable tarpaulin build on stable channel by workaround: disable feature "publish-lockfile" during the build
=> Docker build improvements

src/config/mod.rs, src/lib.rs, src/main.rs
After some trial and error it finally worked.
Fixes #181.
**Questions**
- Instead of `env::var(rustflags)` we should use `build_config.extra_rustc_args` or `build_config.extra_rustc_env`. But I couldn't figure out how they work, I don't consider important for that PR.
- I added `-C debuginfo=2` to all kind of builds, I assume that is not going to have any unintentional effects?
=> Implement `--release` option.

README.md, src/config/mod.rs, src/lib.rs, src/main.rs
I noticed that changing `RUSTFLAGS` should always result into a complete rebuild from scratch by cargo.
Anything else should be considered a bug by cargo.
**Questions**
- `Adds a clean stage to work around cargo bugs that may affect coverage results` is that fine or is that too much?
- `--force-clean` is fine? Maybe `--clean` or `--add-clean-stage`? (these are horrible suggestions I know)
=> Flip around `--skip-clean` and make it `--force-clean`.

Cargo.lock, Cargo.toml, src/report/coveralls.rs
Sends information about current commit and branch to coveralls.io, allowing it to display source code properly.
=> Collect git info for coveralls

Cargo.toml, tests/doc_coverage.rs, tests/line_coverage.rs, tests/mod.rs, tests/utils.rs
On my system(Ubuntu 16 in WSL), tests were failing because the test directory paths were being built incorrectly. For instance: `tarpaulin/tests/data/ifelse/tests/data/proc_macro/Cargo.toml` was one. Instead, paths should be built relative to the `CARGO_MANIFEST_DIR` envvar which Cargo sets and is the location of your Cargo manifest. As a byproduct, this also lets you run `cargo test` in other directories (ie the test dir).
=> Make tests pathing relative to Cargo manifest

src/report/html.rs, src/report/mod.rs, src/report/safe_json.rs
It could happen that measured code contains HTML text ([like this](https://github.com/xd009642/tarpaulin/blob/master/src/report/html.rs#L67-L80)) with `</script>` tag in it. In such situation HTML report doesn't work in browser. So, characters `<`, `>`, and '&' should also be escaped in JSON.
Serde_json allows to specify custom formatter, so this PR wraps default one and adds escape for additional characters.
=> Custom formatter for serde_json to escape HTML specific characters

README.md
A very minor quality of life improvement: the readme's Docker commands can almost be copy/pasted into a PowerShell prompt, but `$PWD:` needs to be `${PWD}:`.
=> Fix readme Docker commands for Windows

CHANGELOG.md, src/config/mod.rs, src/config/parse.rs, src/lib.rs, src/main.rs, src/report/cobertura.rs, src/report/coveralls.rs, src/source_analysis.rs, src/test_loader.rs
ignore lines containing "}else{"
add --manifest-path option
=> calculate relative paths to base_dir (env::current_dir(), or root arg)

CHANGELOG.md, src/config/mod.rs, src/config/parse.rs, src/lib.rs, src/main.rs, src/report/cobertura.rs, src/report/coveralls.rs, src/report/html.rs
Resolves #245 - Adds a new option `--output-dir` that allows the user to specify the target directory to write the reports to. 
I didn't add any automated tests specifically for this, but please let me know if/where I need to add any!
=> add --output-dir option

src/report/cobertura.rs
`Vec::dedup` only removes consecutive elements, but HashSet implicitly dedups regardless of order.
I was running into an issue where codecov was failing to show any files at the root `src/` path. Digging deeper, it turned out that the XML contained multiple `<package name="src" ...>` entries which codecov didn't like. The fix properly generates unique names for the `packages` array.
=> Use HashSet for xml package deduplication

CHANGELOG.md, src/errors/mod.rs, src/lib.rs
Hi, I really like your project!
I recently noticed that supplying `tarpaulin` with either an invalid output directory or an unsupported format, the error messages were a bit weird. For example:
`Output format Format currently unsupported is currently not supported!` or 
`Error: "Output format Failed to create or locate custom output directory: \"/test/dir\" is currently not supported!`
I hope this small fix does the job.
=> Fix invalid output error messages

.github/workflows/rust.yml
By default, GitHub Actions "fails fast;" if one of the builds fails, the rest in the matrix are cancelled, presumably to conserve build minutes.
Since both (i) GitHub Actions is free and unlimited for OSS projects, and (ii) nightly builds are not necessarily a great indication of whether or not a given changeset is actually broken since nightly does break from time to time, it seems wise to prevent failures in e.g. the nightly build from stopping the entire workflow.
Essentially, this PR allows stable/beta builds to continue if nightly fails, but the same does also apply in the other direction.
=> actions: Don't fail-fast the matrix build

src/config/parse.rs
This adds support for relative paths for manifest-path, currently only absolute paths are working.
=> allow relative paths for manifest-path

.github/workflows/rust.yml
This PR changes the Actions configuration to include setup for rustfmt and usage of rustfmt before continuing with the rest of the build. Ideally, poorly-formatted code should trigger the earliest feedback, so `cargo fmt` is run before the rest of the build, on all three versions of Rust.
=> actions: Check formatting before continuing with the build

src/config/parse.rs
This reconciles the changes in #274 and #276 to (hopefully) fix the formatting so that the formatting on `develop` is correct.
=> get_manifest: Reformat canonicalization chain

CHANGELOG.md, src/config/mod.rs, src/lib.rs, src/main.rs
See #247
---
In CI, separating the build and test steps (e.g., to ensure the build doesn't have access to privileged Docker containers to use `ptrace`), the test should take `--frozen` to ensure that the build is up-to-date rather than possibly building the crate again.
=> options: add --frozen and --locked flags

src/report/cobertura.rs
`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Removes the implementation of `description` in `cobertura::Error`
Related PR: https://github.com/rust-lang/rust/pull/66919
=> Remove deprecated Error::description

src/report/cobertura.rs
`Error::cause` has been documented as deprecated since 1.27.0 
This PR:
- Removes the implementation of `cause` in `cobertura::Error`
Related PR: https://github.com/xd009642/tarpaulin/pull/302
=> Remove deprecated Error::cause

README.md
Currently the recommended instructions say to use `cargo install -f`, which always rebuilds tarpaulin even if it's already installed. Removing the -f caches the build if it already exists, which can speed  up builds by 10 minutes or more.
=> Cache tarpaulin on Travis CI

Cargo.toml
Cargo.toml currently specifies a minimum clap version of 2.31.2. However, this is an old
version from March 2018 that cargo-tarpaulin 0.10.0 does not actually compile against.
This is because of a macro issue for Rust 2018 in Clap 2.31.2, where the arg_enum macro
emits a call to the _clap_count_args macro expecting it to be in scope. Since tarpaulin
does not `use clap::macros::_clap_count_args` this is not true, and compilation fails. You can 
observe this by making a new crate which depends on cargo-tarpaulin 0.10.0, or by
updating `Cargo.toml` to specify `"=2.31.2"` instead of `"2.31.2"`
This was fixed in this Dec 2018 commit to `clap`: https://github.com/clap-rs/clap/commit/cfbcb93f94fe8402054945e946bd51ed10b57326#diff-e1576943a5907b15388ab726037ebdb3 which is
included in 2.33.0
Having …
=> Bump required clap version to 2.33.0 in Cargo.toml

tests/data/matches/src/lib.rs, tests/mod.rs
This commit adds an extra scenario to the suite of match expression
tests. It was added because the changes in commit b8b427cdde6f996df20d4dfbf95a4b19d24a76da
add support for it, so now seems like a good time to account for it :smile: 
This commit also adds the matches tests to those run from
`tests/mod.rs`. I'm not actually sure why it was omitted from that file
though, so maybe that's the wrong thing to do :grimacing:
Thanks for taking a look :raised_hands:
=> Add match expr test and run in test suite

README.md
Closes #359
I think it would be great if tarpaulin had CI itself to verify that all
recommended installation procedures actually lead to working setups.
Unfortunately I don't have the time to set that up for you.
=> Clarify needed settings for pre-built binaries.

CHANGELOG.md, src/errors/mod.rs, src/lib.rs, src/report/json.rs, src/report/mod.rs
This PR is based on pull request https://github.com/xd009642/tarpaulin/pull/250. This should provide the same functionality as that pull request, except that I refactored that code in order to expose methods that allowed programmatic access of JSON report contents. The goal is to be able to invoke these methods from an external library in order to access the `CoverageReport` struct.
=> Add json support

Dockerfile, Dockerfile-nightly
Using builder pattern reduced the size from 1.7 GB to 1.2 GB
Using rust-slim reduced the size from 1.2 GB to 0.5 GB
=> Reduce the size of docker builds

CHANGELOG.md, src/source_analysis.rs
---
Ignore `todo!()` just like `unimplemented!()`.
=> source_analysis: ignore todo!() just like unimplemented!()

CHANGELOG.md, src/report/html.rs
When a previous result mentions a non-existent file, just ignore the
error; it has probably just been deleted since the last run (different
branch, reworked source tree, etc.).
Fixes #382
=> html: support coverage diffs with deleted sources

CHANGELOG.md, src/cargo.rs
This closes #404 
This fixes a problem where toolchains that are locked by date will be overridden by Tarpaulin.
I'm not entirely sure if there are any edge cases this won't handle in terms of toolchains, but the notation `cargo +<toolchain> command` should allow the full toolchain name just fine.
Please let me know if anything needs to be changed :smiley:
=> Added full toolchain name to create_command

CHANGELOG.md, src/config/mod.rs, src/config/parse.rs, src/report/cobertura.rs, src/report/coveralls.rs, src/report/html.rs, src/report/json.rs, src/report/lcov.rs, src/report/mod.rs
This PR allows more config items to be specified on the command line and override an existing config file on an adhoc basis to allow for per run or per environment overrides.
In particular, it adds support for overriding the following options:
* Target directory for Rust builds, for example if a CI build needs to output to a specific cached location.
* Output directory for Tarpaulin output, for the same reason
* Coveralls related config items (coveralls, ci_tool and report_uri). Primarily the coveralls flag was desired, to allow use in environments other than Travis which require access to a secret API key that you may not wish to include in repo, but I included all three options for consistency.
* Crate root, to allow for a run to target only a single crate in a workspace.
Previous …
=> Allow more CLI options to override config file.

CHANGELOG.md, src/config/parse.rs
Fixes: #383 
---
This allows users to change the default target directory for their own environment without having to add `tarpaulin.toml` files to every repository changing it for every developer.
=> config: support CARGO_TARPAULIN_TARGET_DIR as a source for the target dir

README.md
**WIP**: Waiting for the upstream package to be merged: [nixos/nixpkgs#87571](https://github.com/NixOS/nixpkgs/pull/87571).
Add [Nix](https://nixos.org/nix/) installation instructions to the README. This may be considered an unnecessary addition, if so, I am fine with the PR being closed permanently.
The addition is aimed to direct Nix users to the necessary package for installing cargo-tarpaulin. For Nix users, using the nix package installation method instead of the `cargo install` method is advisable as it ensures tarpaulin is built using the rust version specified by the user.
=> README: Add nix installation instructions

CHANGELOG.md, src/lib.rs
When using `--no-run` no coverage should be reported since no tests has been executed.
=> Don't report coverage when not running tests

Cargo.lock, Cargo.toml
Add a feature for using the `vendored-openssl` feature in `git2`. This will allow `openssl-sys` to compile OpenSSL from source: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/Cargo.toml#L15
It is useful for installing tarpaulin on environments that don't have OpenSSL.
=> add feature for using vendored openssl

Cargo.lock, Cargo.toml, src/cargo.rs, src/config/mod.rs, src/config/parse.rs, src/event_log.rs, src/lib.rs, src/main.rs, src/report/coveralls.rs, src/report/mod.rs, src/source_analysis/mod.rs, src/statemachine/linux.rs, src/statemachine/mod.rs, src/test_loader.rs, src/traces.rs
- replace `use log::{..}` with `use tracing::{..}`
- replace the env_logger with tracing-subscriber
- keep most of the behavior (variables debug and verbose) which set the default tracing mode.
- CHANGE BEHAVIOR: RUST_LOG now can overwrite debug and verbose, you can also use it to overwrite it only partially
(i wasn't able to run all the tests locally)
(maybe we need to `tracing-log` crate, in order to capture dependencies logs)
First steps of #545 . It still needs a check if the current logging is good.
Also note:
- I had serious problems running tarpaulins tests. So i can't say if it works perfectly.
- removed a useless `use std::io::Write;`
=> move to tracing crate

CHANGELOG.md, src/path_utils.rs, src/test_loader.rs
* Rearrange the logic to be correct all the time with header includes
* is_coverable_file now check if file is in project directory as well not just if it's in bad directories
* Add tests
=> Rearrange is_coverable_file ordering in test_loader

CHANGELOG.md, src/cargo.rs, src/config/mod.rs, src/main.rs
I created this pull request in order to avoid "cannot find attribute" error that comes from `#[cfg_attr(tarpaulin, skip)]` in some old dependencies.
In the project I use `glutin` that uses `wayland-commons v0.21.13`. When I want to check coverage using tarpaulin I get:
> "Error: cannot find attribute \`skip\` in this scope"
`--avoid-cfg-tarpaulin` flag removes `--cfg=tarpaulin` from the `RUSTFLAGS`.
Do you agree to add such a flag?
Thanks in advance.
=> Add avoid-cfg-tarpaulin flag

CHANGELOG.md, src/cargo.rs
Now trying to match on a minimal representation of the path
=> Workspace naming convention seems to have changed

CHANGELOG.md, src/event_log.rs, src/statemachine/linux.rs, src/traces.rs
In the debug logs add some source information just so I can see which
lines are hit in what order. Initial impl
=> Source location traces

CHANGELOG.md, src/cargo.rs, tests/line_coverage.rs
This detects if the user has set -Cdebuginfo in their rustflags and
removes this as tarpaulin sets it and requires it to get debug info for
traces.
=> Fixes #601

.github/workflows/rust.yml, CHANGELOG.md, src/cargo.rs
Once again the binary naming scheme has changed. Hopefully this is
generic enough without being too generic so it works.
I also thought there was a need to know the version but scrapped that
but the code is nice and useful for other things so keeping it
=> Attempt to fix doctests

src/config/mod.rs, src/path_utils.rs
Comparing path equality with strings wasn't smart now was it
=> Fix path comparison in windows

CHANGELOG.md, src/cargo.rs, src/config/mod.rs, src/config/parse.rs, src/main.rs
Allow rustflags to be passed via arg and therefore via config file
=> initial implementation rustflags arg #689

CHANGELOG.md, src/cargo.rs, src/process_handling/linux.rs, tests/test_types.rs
Also noticed that the default cleaning deletes the whole target irectory
including the previous tarpaulin results. So moved to deleting just the
artefact folders so between run deltas are still reported
=> Reduce the number of the cleans for #747

src/cargo.rs
I think it there is no Easter egg for `cargo` to put release build in `${CARGO_TARGET_DIR}/debug`
=> Fix cleaning for wrong directory

README.md
Since there is already a docker image, we can refer to use this
=> use existing tarpaulin image

CHANGELOG.md, src/cargo.rs
Handles instance where rustflags can be a string instead of just a list
=> Fixes #797

CHANGELOG.md, src/config/mod.rs, src/main.rs
This change allows to see config parse errors. Entire conf vector is also dumped for additional verification if `trace` enabled.
The motivation for this PR is that it is quite difficult to get the configuration file correctly quickly as parse errors will not be reported. I encountered this problem while trying to write a config file, where I needed to combine several `cargo test` runs into a single coverage report.
=> feat(config): log config parsing

README.md
Thanks for the great tool!
I just set up my project for coverage reports with `tarpaulin`, and found I can do more than the README.md lets on, so here we go :)
- Add instructions how to set up highlighting coverage status of lines in Gitlab MRs.
- Describe another way to specify the coverage regex for a specific job, in `gitlab-ci.yml`.
=> Expand gitlab section in README.md

CHANGELOG.md, src/process_handling/linux.rs
As discussed in #817, this change sets the processor affinity to the lowest core id of the existing affinity mask. This will solve cases where the core id 0, which was previously used, is not available (e.g. in virtualized environments).
(fixes #817)
=> Use core from existing mask when setting processor affinity

Cargo.toml, README.md
As per (I think): https://twitter.com/xd009642/status/1435639358531452928
For context:
Cargo Binstall provides a one-stop tool to install binaries from the CLI. It's a bit rough around the edges but works well in most cases. This PR adds the metadata needed to get it going (from the next release)!
To test this before the next release / cargo publish:
```
cd repo
git checkout the branch
cargo binstall --manifest-path . --log-level debug cargo-tarpaulin
```
=> Add support for binstall

src/source_analysis/attributes.rs, src/source_analysis/tests.rs
This adds the unstable rustc attribute for skipping coverage of items.
Fixes #860.
=> feat: Add unstable `#[no_coverage]` attribute to ignore set

CHANGELOG.md, src/report/cobertura.rs
Change it to use TraceMap::coverage_percentage so results match
=> Change report line-rate (#873) fixes #872

src/path_utils.rs
It is known that `tarpaulin` will look for coverage data in vendored
crates if `cargo-vendor` is used (#210). It is reasonably simple to
exclude the vendored crates though the `--exclude-files` option.
However, all of the sources is still collected even if they are not
treated as covered. This is quite obvious when using the `Html` report
format for example which becomes huge because it contains the crate
sources as well as all the vendored crates' source files.
To avoid this, apply the excluded files filter at the earliest point,
i.e., when walking the crate source tree and finding all the rust source
files.
---
Small example:
```bash
cargo new tarpaulin-vendor-reprod
```
`Cargo.toml`:
```toml
[package]
name = "tarpaulin-vendor-reprod"
version = "0.1.0"
edition = "2021"
[dependencies] …
```
=> Exclude files already when walking source tree

CHANGELOG.md, src/cargo.rs, tests/data/rustflags/src/lib.rs
In theory this should improve incremental compilation via --skip-clean
Fixes #891
=> Implement pruning of flags to remove duplicates

.github/workflows/rust.yml, CHANGELOG.md, src/cargo.rs, src/config/mod.rs, tests/doc_coverage.rs, tests/failure_thresholds.rs, tests/failures.rs, tests/line_coverage.rs, tests/mod.rs, tests/test_types.rs, tests/workspaces.rs
This adds skip-clean to the config file and yet again makes config stuff
a smidge more complicated with prioritisation of antonyms. However, this
seems an acceptable level of complexity
=> Implement skip-clean in config file Fixes #922

src/cargo.rs
The workaround isn't needed anymore since https://github.com/rust-lang/rust/issues/85461 is now fixed on Nightly.
Working for me on `x86_64-pc-windows-msvc` and `1.59.0-nightly (fcef61230 2021-12-17)`
=> Remove LLVM codegen-units Windows workaround

CHANGELOG.md, src/cargo.rs, src/process_handling/mod.rs
The results vector is already passed into `run_cargo` so the package id
vector can be misaligned
=> Fixes #921

src/event_log.rs, src/lib.rs, src/traces.rs
=> use lossless conversions where available

src/statemachine/linux.rs
this line creates a mutable reference to a mutable reference. this can be flattened
=> remove mutable double reference

src/cargo.rs, src/report/cobertura.rs, src/report/coveralls.rs, src/report/mod.rs, src/source_analysis/expressions.rs, src/source_analysis/items.rs, src/source_analysis/macros.rs, src/source_analysis/mod.rs, src/source_analysis/tests.rs, src/traces.rs, tests/line_coverage.rs
this PR removes quite a few `collect` calls at the expense (probably) of readability. In particular it complicates a few function signatures my introducing opaque types.
I'm not sure how much of a performance bottleneck these are anyway, but i leave it up to you what you want to do with this.
=> remove a couple of allocations

CHANGELOG.md, src/config/mod.rs
Merging of force-clean now means it's respected in tarpaulin.toml if set
to false
=> Change merging of force-clean

CHANGELOG.md, src/cargo.rs
Very minor thing but impacts detecting llvm coverage support in some beta versions which will become very relevant soon.
=> Fix cargo version string regex

CHANGELOG.md, src/cargo.rs, tests/mod.rs
Forward RUSTC_BOOTSTRAP onto cargo
=> Fixes #1074

src/cargo.rs, src/errors/mod.rs
This PR improves build error messages to make it easier to understand why tests are failing to build. This would greatly help users who get hard to debug build error messages, e.g. https://github.com/xd009642/tarpaulin/issues/517
Build error message before changes:
```
Aug 18 18:30:01.312 ERROR cargo_tarpaulin: Failed to compile tests! Error: rust_sample: mismatched types
Error: "Failed to compile tests! Error: rust_sample: mismatched types"
```
Build error message after changes:
```
Aug 18 18:45:43.885 ERROR cargo_tarpaulin: Failed to compile tests!
error[E0308]: mismatched types
--> src/lib.rs:5:5
|
1 | fn get_message(hello: bool) -> String {
|                                ------ expected `String` because of return type
...
5 |     "Hello, world!"
|     ^^^^^^^^^^^^^^^- help: try …
```
=> Improve build error messages

src/errors/mod.rs, src/report/mod.rs
This PR just adds 2-decimal point precision to the display for the coverage % delta and one error `Display` impl that also displays percentages.
=> Add 2-decimal point display precision for the report coverage % delta

.github/workflows/rust.yml
When submitting #1101, I noticed the CI took a long time.
On all of my projects, I use https://github.com/marketplace/actions/rust-cache, which caches the compiled dependencies so that only the final executable is rebuilt on every push/PR. This should significantly speed up successive CI runs. (less so for nightly builds because the cache is invalidated daily)
I noticed on the Linux job, there was a `cargo clean` step that wasn't done on Windows or Mac. Because that would defeat the point of caching compiled dependencies, I removed it.
I also noticed the `RUST_BACKTRACE` environment variable was set individually, and moved that to a global workflow-level environment variable, so it applies everywhere. If that was a mistake, and it was applied individually for a reason, I can move it back.
=> Add `rust-cache` to the CI workflow.

src/report/report_viewer.js
This PR slightly improves generated HTML report by helping keyboard-only users to navigate within the report.
Tested on Chome and Firefox browsers and Vimium C and Vimium FF extensions respectively.
When browsing Tarpaulin HTML report in a Browser (I've tried Firefox and Chrome), a mouse has to be used to navigate in the report (mouse-click on files and folder table rows). This is probably fine for most of users, since I assume most people do actively use mouse all the time.
However, among SW developers, there is (maybe small, but arguably growing) group of keyboard-only users, whom
consider the need of grabbing a mouse and making that mouse-clicks an unnecessary distraction in the workflow.
One way to retain a keyboard-only navigation in web pages is to extensions like Vimium. They rely …
=> Extra `<a>` elements added to HTML report.

.github/workflows/release.yml
Tentatively fix https://github.com/xd009642/tarpaulin/actions/runs/3498060423/jobs/5858366657#step:3:134 where the musl toolchain is not found.
=> Fix release workflow broken by a1bfc4ff6

.github/workflows/release.yml, Cargo.toml, build.rs
As said in https://github.com/taiki-e/install-action/pull/42#issuecomment-1372184541, I would like to help improve release staff. (If work on this is in progress on your end and you do not need this patch, feel free to close this PR.)
This patch updates the release workflow and makes the release work on x86_64 linux-gnu/linux-musl/macos/windows and aarch64 linux-gnu/linux-musl/macos. The following are specific changes:
- Add x86_64/aarch64 linux-musl
- Closes https://github.com/xd009642/tarpaulin/issues/1130
- Remove aarch64 windows.
- ~~aarch64 linux fails to build [^1]: https://github.com/taiki-e/tarpaulin/actions/runs/3875026523/jobs/6606999714~~ EDIT: fixed in https://github.com/xd009642/tarpaulin/pull/1174/commits/5476833acd2cf994ebecba6949d29aeb74a857e7
- aarch64 windows doesn't …
=> Update release workflow

CHANGELOG.md, src/event_log.rs, src/lib.rs, tests/mod.rs
This keeps things somewhat consistent as it's a report and makes it easier for people to keep project root clean of extraneous files
=> Save event log to report directory

CHANGELOG.md, src/cargo.rs, src/event_log.rs, src/process_handling/mod.rs
`-C instrument-code` causes build scripts to generate profraw files in the root directory. This also means for every build script executed you get another profraw. I fix this by moving to a profraw file name that will clash resulting in only one file and then deleting it after the tests are built.
=> Fixes #1183

src/traces.rs
Clippy has a rules which warns when you are re-implementing a core function
in this case "find" was being implemented.
Here is a description of the rule [find rule](https://rust-lang.github.io/rust-clippy/master/index.html#manual_find)
=> Clippy: was re-implementing find() call.

src/branching/mod.rs, src/cargo.rs, src/config/mod.rs, src/errors/mod.rs, src/event_log.rs, src/lib.rs, src/main.rs, src/process_handling/linux.rs, src/process_handling/mod.rs, src/report/cobertura.rs, src/report/coveralls.rs, src/report/html.rs, src/report/lcov.rs, src/report/mod.rs, src/statemachine/linux.rs, src/test_loader.rs, src/traces.rs
When I run ```cargo clippy``` the output is so large that it is difficult to reason with 
So I have cherry picked a single frequently repeated  warning to make the review process simpler, and to make the list more manageable.
All the changes are of the form 
```rust
-    acc.push(format!("{}-{}", first, last));
+    acc.push(format!("{first}-{last}"));
```
=> Clippy: Improve readablility when formatting strings.

src/process_handling/mod.rs
Clippy has spotted a .clone() call which can be removed.
[iter_cloned_collect](https://rust-lang.github.io/rust-clippy/master/index.html#iter_cloned_collect)
=> Clippy: Simplify iter_cloned_collect

src/event_log.rs, src/statemachine/instrumented.rs
Note: this PR targets the `fix/canonicalise-object` branch, not `develop`.
I need one other change to fully fix #1156 for me: the supplementary objects are only created in the middle of the test suite, so trying to access it before results in "file not found". I think the simplest solution is to check if the file exists before trying to parse it, informing the user if the file is skipped so that typos can be corrected.
=> More fixes for supplementary objects

src/source_analysis/attributes.rs, src/source_analysis/tests.rs
Addressing https://github.com/xd009642/tarpaulin/issues/1220
Added the ability to ignore functions that are prefixed with an attribute ending with `test`.
Added matching automated tests.
=> Added filtering of attributes that end with 'test' like tokio::test

.github/workflows/coverage.yml, .github/workflows/docker.yml, .github/workflows/rust.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.5.2
> - Fix api endpoint for GHES
>
> ## v3.5.1
> - Fix slow checkout on Windows
>
> ## v3.5.0
> - Add new public key for known_hosts
>
> ## v3.4.0
> - Upgrade codeql actions to v2
> - Upgrade dependencies
> - Upgrade @actions/io
>
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - …
=> Update actions/checkout in GitHub Actions workflows to v3

src/cargo.rs
Cargo from distro packages does not contain a date, which results in the version not getting parsed.
e.g.:
```
$ cargo --version
cargo 1.66.1
```
The date is not being used anywhere, so I just removed it.
=> Simplify cargo version parsing

CHANGELOG.md, src/cargo.rs
This will broaden the prefix name to increase the list of possible matches
=> Fixes #1315

src/config/mod.rs, src/source_analysis/attributes.rs, src/source_analysis/items.rs, src/source_analysis/mod.rs, src/source_analysis/tests.rs, src/test_loader.rs, tests/mod.rs, tests/test_types.rs, tests/workspaces.rs
This commit 343e912bf33a3872ff9f49d48686831d7ca701da made `ignore-tests` the default flag and added `include-tests` flag to reapply the old behaviour. But, the [ignore_tests](https://github.com/xd009642/tarpaulin/commit/343e912bf33a3872ff9f49d48686831d7ca701da#diff-b0ba3e54b6f5ef1fa6aed8075e352a68fda66067fbafa8421042a2347801338aR392) function will always return `true` even if `include-tests` is set. This is because of the logical OR operator `||` used.
- Removed `ignore_tests` from `Config` as both `ignore_tests` and `include_tests` are inverse to each other and can be deferred from a single boolean. 
- Removed `set_ignore_tests` and added `set_include_tests`.
- Removed `ignore_tests` and added `include_tests`.
- Made required changes to use the new  `set_include_tests` and …
=> Fix include-tests

CHANGELOG.md, src/args.rs, src/config/mod.rs, src/lib.rs
When running code coverage on bigger projects, if test fails, tests for all other libraries and binaries are still runned, it would be nice to have a option to fail immediately after single test fails, like `cargo test` does.
Closes #1373
=> added option to fail immediately after single test fails

Cargo.toml
`cargo binstall cargo-tarpaulin` currently installs from source on Windows, despite releases being available for that platform in the repository.
The root cause is that the `.tar.gz` extension is explicitly specified in the `pkg-url` under `[package.metadata.binstall]`.
Replacing that extension with `{ archive-suffix }` is sufficient to make this work.
=> Update Cargo.toml to allow cargo-binstall on windows

README.md
With the latest release, the possible values for `--out` changed from a Rust type-like `Foo` to 
`foo`. I noticed this when a GitHub action failed due to an invalid `--out` value.
This PR naively replaces `--out Xml` with `--out xml`, there may be more documentation issues, but 
I'm getting this PR out to raise the issue and get a fix started.
=> docs: Fix `--out` option

README.md
Fixes extra spaces between keys and values to align with the normal styling used throughout the README
=> docs: fix indentation in coverage workflow

src/report/report_viewer.css
This should fix the first part of #1433.
It keeps the top bar stuck to the top of the window when scrolling down.
The crucial part `sticky` is pretty well supported across browsers. 
https://caniuse.com/css-sticky
=> Make header stick to the top even when scrolling down

src/report/report_viewer.css, src/report/report_viewer.js
Follow up on #1433 to add line numbers.
The line-numbers are done with CSS and will not be selected/copied when selecting/copying code.
Here is a screenshot from the tarpaulin repo
=> Line numbers in reports

README.md
The link to "Test Coverage Visualization" for GitLab has changed and no automated redirect is available.
=> Update link to GitLab "Test Coverage Visualization" doc

src/args.rs
- cargo test has `--package` and `-p`
- cargo tarpaulin has `--packages` and `-p`
I think it would be nice if cargo tarpaulin also had `--package` as an alias to make it easier going between these tools.
https://github.com/xd009642/tarpaulin/issues/1477
=> Add --package alias to mimic `cargo test` interface

src/source_analysis/items.rs, src/source_analysis/tests.rs
Motivation:
The original issue is sorta described here: https://github.com/xd009642/tarpaulin/issues/351#issuecomment-2036231706. 
But tl;dr version is when `include-tests` is set, `#[tokio::test]` is not covered in the coverage report. 
Changes in this PR:
Added an additional condition to `visit_fn` to check whether the `PathSegment`s ends in `test`, such as `#[tokio::test]` or `#[some_fancy_crate::test]`. 
I tested this tarpaulin version against the issue that I was originally encountering, and it seems to fix it.  
Before where `#[tokio::test]` was ignored: https://app.codecov.io/gh/kube-rs/kube/blob/cov-tweak/kube-runtime%2Fsrc%2Fcontroller%2Ffuture_hash_map.rs#L85
After where it's now included: https://app.codecov.io/gh/tyrone-wu/kube/blob/main/kube-runtime%2Fsrc%2Fcontroller%2Ffuture …
=> Fix `include-test` config to include non-std test

.github/workflows/rust.yml, Cargo.toml
I noticed the build is currently failing on 32bit x86 when trying to [package cargo-tarpaulin for Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/59413).
In the github actions workflow I noticed there's a test matrix defined for i686, but without `--target` it only runs for the default target (x86_64).
=> Add missing --target to make use of ${{ matrix.target }}

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib.rs, src/process_handling/mod.rs, src/statemachine/instrumented.rs, tests/mod.rs
Also pull in PR branch of llvm-profparsers to let it know it can fail to parse some of the binaries. This issue was caused by spawned processes not having the instrumentation and being included in the affected binary list!
=> Propagate rustflags to test binaries

src/cargo.rs
Previously, if your rustup was installed to a different location than the default, tarpaulin would erroneously try to add the toolchain. Now it doesn't!
I tested this on my machine and it finally worked. This correctly resolves #1494, though I'm not sure if standard installs will work correctly (they should though).
=> Check for RUSTUP_HOME when deciding whether to override the toolchain or not.

Cargo.lock
I was about to update the cargo-tarpaulin package on Alpine (and remove the `!x86` rule), but then noticed the latest release doesn't build on Alpine.
This is due to a compatibility issue in the jobserver crate but can be fixed by updating to the latest version (which this PR does).
```
Compiling fnv v1.0.7                 ] 37/257: libc, jobserver, syn, syn, unicode-segmentation, mio, socket2,...
Compiling tinyvec_macros v0.1.1      ] 38/257: fnv, jobserver, syn, syn, unicode-segmentation, mio, socket2, ...
error[E0425]: cannot find function `preadv2` in crate `libc` syn, syn, unicode-segmentation, mio, tinyvec_macros...
--> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jobserver-0.1.29/src/unix.rs:598:15
|
598  |           libc::preadv2(
|                 ^^^^^^^ help: …
```
=> Update dependencies, fix build on Alpine/musl libc

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/source_analysis/tests.rs, tests/doc_coverage.rs, tests/failure_thresholds.rs, tests/failures.rs, tests/line_coverage.rs, tests/mod.rs, tests/test_types.rs, tests/workspaces.rs
With this removed the complete removal of syn1.x will be complete once ruztd is released and object is updated to use it (or semver allowing I can just update ruztd myself and object doesn't have to release).
Another important step in eradicating syn1
=> Remove tracing-test

CHANGELOG.md, src/main.rs
No longer print rustflags for report configs with `--print-rust-flags`
=> Fixes #1555

.github/workflows/rust.yml, Cargo.toml, src/args.rs, src/config/mod.rs, src/config/parse.rs, src/config/types.rs, src/report/mod.rs
This PR aims to make the coveralls api crate and git2 optional to avoid needing to pull in openssl unnecessarily.
=> Fixes #1582

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Update llvm profparsers

src/traces.rs
This looks like a left-over debug `println!` but it's causing issues in [`cargo2junit`](https://github.com/johnterickson/cargo2junit) when using it together with `cargo-tarpaulin`:
```sh
RUSTC_BOOTSTRAP=1 cargo tarpaulin --out Xml --skip-clean --target-dir target-tarpaulin \
-- -Z unstable-options --format json --report-time | cargo2junit > report.xml
```
`cargo-tarpaulin` is writing it's own report file, but the rustc output of `--format json` is also processed by `cargo2junit` at the same time (to avoid running `cargo test` twice).
`cargo2junit` is trying to detect rustc output by looking for lines starting with `{`, this is also the case for `std::fmt::Debug` of the HashMap (while not valid json), causing the `cargo2junit` parser the fail.
This patch solves this by removing the debug …
=> Remove HashMap println! in set_functions

CHANGELOG.md, README.md, src/config/mod.rs
With this commit, tarpaulin will try to get the path to the configuration file (usually `tarpaulin.toml`) from the environment variable `CARGO_TARPAULIN_CONFIG_FILE` first, before proceeding with trying `tarpaulin.toml` and `.tarpaulin.toml`. The motivation of this PR is, that I have multiple repositories with the same tarpaulin-config. With https://direnv.net/, I am able to set environment variables, which would allow me to set `CARGO_TARPAULIN_CONFIG_FILE`, thus avoiding duplicate configurations. Symlinks are not really an option with repositories.
=> feat: try to get path to config-file from `CARGO_TARPAULIN_CONFIG_FILE`

README.md, src/args.rs, src/config/mod.rs, src/path_utils.rs, src/test_loader.rs, tarpaulin.toml
Added the flag `--include-files` to tarpaulin to only have a select amount of files that we get coverage from. It can save some time, as we are not looking at the traces of excluded files.
A condition has been added in the include_path function to make sure that --include-files is deactivated when no argument has been passed: otherwise, this would exclude all files from the report (as --include-files excludes all files by default).
Pretty much copied from the `--exclude-files` feature. Added some tests to make sure everything was working fine.
Here are some commands that I tested on another Rust project from the built image:
cargo tarpaulin --include-files src/jwt/mod.rs --out xml --> SUCCESS only 5 lines seen, 60% coverage
cargo tarpaulin --include-files src/jwt/* --exclude-files …
=> Added feature --include-files

src/process_handling/mod.rs
#1621 and other past likely closed issues where people expected the args passed to the test binary were for their test and not to be consumed by cargo test should hopefully be fixed by this.
=> Move test threads to env var not CLI arg

src/cargo.rs, tests/data/doctest_workspace_should_panic/Cargo.toml, tests/data/doctest_workspace_should_panic/foo-bar/Cargo.toml, tests/data/doctest_workspace_should_panic/foo-bar/src/lib.rs
When trying out the doctest support on a workspace involving many `kebab-case` named crates I noticed any `should_panic` doctests were failing.
I didn't manage to run the tests to confirm the added test reproduces it properly, I'm getting crashes inside the test runner on `develop` too. I'll spend a little more time tomorrow trying to diagnose what about my weird setup the test runner doesn't like.
=> Handle doctests file paths that contain dashes

src/config/mod.rs, src/traces.rs
Add explicit lifetime parameters to get_metadata() and iter() return types to comply with Rust lifetime elision requirements.
Fix the compilation warnings in the latest stable Rust version 1.89.0 .
> [Add a warn-by-default mismatched_lifetime_syntaxes lint.](https://github.com/rust-lang/rust/pull/138677) This lint detects when the same lifetime is referred to by different syntax categories between function arguments and return values, which can be confusing to read, especially in unsafe code. This lint supersedes the warn-by-default elided_named_lifetimes lint.
=> Add explicit lifetime annotations to return types
