xd009642/tarpaulin

README.md

Because copypasta is the best pasta.

Add an `Installation` section to usage

---

src/config.rs
src/lib.rs
src/personality.rs
src/report/coveralls.rs
src/report/mod.rs
src/tracer.rs

Mostly small readability things, the code is already quite good :+1:

fixed some clippy warnings

---

Cargo.lock
Cargo.toml
src/breakpoint.rs
src/lib.rs
src/ptrace_control.rs

At least it compiles and tests are passed :)
Related to https://github.com/xd009642/tarpaulin/issues/45

update nix to 0.9.0

---

Cargo.lock
Cargo.toml
src/tracer.rs

Here is my attempt to help.
Related to https://github.com/xd009642/tarpaulin/issues/45

Update gimli to 0.14.0

---

README.md

"Build status link" was not working.

fix link to travis ci build from readme

---

README.md

README: Add instructions for usage with Docker

---

README.md

Refs [#74](https://github.com/xd009642/tarpaulin/issues/74)

Update dependencies for Debian in README

---

src/lib.rs
src/source_analysis.rs
src/test_loader.rs

similar to https://github.com/xd009642/tarpaulin/pull/143

cleanup trailing spaces

---

Cargo.lock
Cargo.toml
src/config/types.rs
src/lib.rs
src/report/html.rs
src/report/mod.rs
src/report/report_viewer.css
src/report/report_viewer.js
src/traces.rs

Related to https://github.com/xd009642/tarpaulin/issues/55

Initial version of HTML report

---

src/report/report_viewer.js

Related to https://github.com/xd009642/tarpaulin/issues/230

Persistent URLs in HTML report

---

src/report/report_viewer.js

Improve navigation in HTML report

---

src/breakpoint.rs
src/config/mod.rs
src/lib.rs
src/main.rs
src/report/cobertura.rs
src/report/html.rs
src/report/mod.rs
src/report/safe_json.rs
src/source_analysis.rs
src/statemachine/linux.rs
src/statemachine/mod.rs
src/test_loader.rs
tests/compile_fail.rs
tests/mod.rs

I ran 'cargo fmt' to format the code

Format code using 'cargo fmt'

---

CHANGELOG.md
src/config/types.rs
src/errors/mod.rs
src/report/info.rs
src/report/lcov.rs
src/report/mod.rs
src/test_loader.rs
src/traces.rs

* Added lcov.info support (#287)
* Added function names to traces

Support for lcov.info

---

CHANGELOG.md
src/report/html.rs
src/report/report_viewer.js

Coverage change for files in the report
Implementation for https://github.com/xd009642/tarpaulin/issues/284

Coverage change added to HTML report

---

.github/workflows/release.yml
.github/workflows/rust.yml

Bumps github action `checkout` from v1 to v2

bump github action checkout to v2

---

Cargo.lock
Cargo.toml
src/config/types.rs

This might be a breaking change because of changing Err item in FromStr.

chore: Favor std Infallible over Void

---

src/cargo.rs
src/config/mod.rs
src/main.rs
src/report/lcov.rs
src/statemachine/mod.rs
tests/mod.rs
tests/test_types.rs

Rather small changes that don't change functionality but rather made the code more readable.
All changes found by using clippy.

Some Improvements

---

src/config/mod.rs
src/source_analysis/attributes.rs
src/source_analysis/mod.rs
src/test_loader.rs

Adds a few small style improvements / suggestions form clippy.

Style improvements

---

CHANGELOG.md
src/config/mod.rs
src/main.rs
src/source_analysis/attributes.rs
src/statemachine/linux.rs
src/statemachine/mod.rs
tests/data/follow_exe/tests/launcher.rs
tests/mod.rs

Fix unhandled tids

---

src/config/mod.rs
src/config/parse.rs
src/statemachine/linux.rs
tests/data/tarpaulin.toml
tests/workspaces.rs

Handle config file paths better to fix #631

Initial version of 631 fix

---

CHANGELOG.md
src/event_log.rs

Measure time of events in seconds during run

---

CHANGELOG.md
src/process_handling/breakpoint.rs
src/statemachine/linux.rs
src/test_loader.rs
src/traces.rs

https://github.com/xd009642/tarpaulin/issues/769

Work on fixing address clashing issue

---

CHANGELOG.md
src/process_handling/mod.rs
tests/line_coverage.rs

Fixes #819

---

CHANGELOG.md
src/source_analysis/expressions.rs
src/source_analysis/items.rs
src/source_analysis/mod.rs
src/source_analysis/statements.rs
src/source_analysis/tests.rs

Factor in early returns to source analysis (and fix an also uncovered bug due to it)

Fix/unreachable analysis (fixes #833)

---

CHANGELOG.md

Add guard for if there are no lines in a package

Fixes #869

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/process_handling/linux.rs
src/process_handling/mod.rs

Fixes #885 #892 by explicitly setting the --test-threads for a test

Explicitly set the test threads

---

src/process_handling/linux.rs

Apply affinity limit only to fork child

---

CHANGELOG.md
src/process_handling/mod.rs

Implement RUST_TEST_THREADS handling

---

src/branching/mod.rs
src/cargo.rs
src/config/mod.rs
src/config/parse.rs
src/lib.rs
src/main.rs
src/path_utils.rs
src/process_handling/linux.rs
src/process_handling/mod.rs
src/report/cobertura.rs
src/report/coveralls.rs
src/report/html.rs
src/report/lcov.rs
src/report/mod.rs
src/source_analysis/mod.rs
src/statemachine/instrumented.rs
src/statemachine/linux.rs
src/test_loader.rs
src/traces.rs
tests/mod.rs
tests/workspaces.rs

a bunch of small, pedantic, and generally pointless refactors

address a bunch of nit-picky clippy lints

---

src/source_analysis/items.rs
src/source_analysis/mod.rs

there are a couple of range expressions that can be simplified

use inclusive ranges

---

CHANGELOG.md
Cargo.lock
Cargo.toml
travis-install.sh

Do release commit for 0.20.0

---

src/lib.rs
src/main.rs
src/report/cobertura.rs
src/statemachine/linux.rs

Hi there
I was (once again) reading some code here and there then noticed `clippy` issues + some duplication.
So I decided to do something
Take care.

Refactoring

---

Cargo.lock
Cargo.toml

Minimise nix features

---

CHANGELOG.md
src/source_analysis/mod.rs
src/test_loader.rs
tests/data/breaks/src/lib.rs
tests/data/continues/src/lib.rs

Prevent tracing lines beyond the end of the file or before the start of
the file

Add line filtering

---

CHANGELOG.md
src/config/types.rs
src/report/mod.rs

Add explicit stdout report

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
travis-install.sh

Prepare release 0.20.1

---

tests/data/HttptestAndReqwest/Cargo.lock
tests/data/HttptestAndReqwest/Cargo.toml

Bump version

---

.github/workflows/rust.yml

Disable coverage optionally

---

.github/workflows/rust.yml
CHANGELOG.md
src/config/mod.rs
src/config/parse.rs
src/lib.rs
tests/doc_coverage.rs
tests/failure_thresholds.rs
tests/failures.rs
tests/line_coverage.rs
tests/mod.rs
tests/test_types.rs

on pull request target

---

CHANGELOG.md
src/process_handling/mod.rs

Reorder existing profraw and test spawn

---

.github/workflows/release.yml

(Hopefully) fixes issues #1129 and #1130.

Fix x86_64-unknown-linux-gnu release filename and add one for x86_64-unknown-linux-musl

---

.github/workflows/release.yml

Try to fix release CI

---

CHANGELOG.md
src/cargo.rs
tests/data/rustflags/.cargo/config.toml
tests/data/rustflags/src/lib.rs
tests/doc_coverage.rs
tests/mod.rs

Refactor config file to get rustdocflags as well

---

CHANGELOG.md
src/config/mod.rs

Change default out dir

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/config/mod.rs
src/config/parse.rs
tests/mod.rs

Use glob crate instead of regex

---

src/config/mod.rs

fix output path (with relative directories)

---

CHANGELOG.md
src/path_utils.rs
src/process_handling/mod.rs
src/statemachine/instrumented.rs

Make profile files appear in target folder

---

Cargo.lock
Cargo.toml
src/report/coveralls.rs
src/report/lcov.rs

Sanity test coveralls git info filling

---

.github/workflows/rust.yml
src/main.rs
tests/data/workspace/.gitignore
tests/mod.rs

Add more tests again

---

CHANGELOG.md
src/config/mod.rs
src/config/parse.rs
src/lib.rs
src/main.rs
src/statemachine/instrumented.rs

Fixes #1156 Add something to load other object files

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
src/cargo.rs
src/config/mod.rs
src/main.rs

Fixes #1092

---

CHANGELOG.md
src/source_analysis/attributes.rs
src/source_analysis/tests.rs

Look at cfg_attr in more detail

Fixes #1160 

---

src/cargo.rs
src/config/mod.rs
src/config/parse.rs
src/path_utils.rs
src/process_handling/mod.rs
src/report/coveralls.rs
src/source_analysis/mod.rs
src/statemachine/instrumented.rs
src/statemachine/linux.rs
src/test_loader.rs
tests/mod.rs

Next round of clippy fixes.
The only thing to note is that a .clone() has been removed.

Clippy assorted fixs, one .clone() removal.

---

CHANGELOG.md
src/config/parse.rs
src/event_log.rs
src/statemachine/instrumented.rs

Reshift order of when we canonicalise

---

Cargo.lock

Update llvm profparser

---

src/cargo.rs
src/process_handling/breakpoint.rs
src/source_analysis/mod.rs
src/statemachine/linux.rs

This pull request fixes a few typos, no functional changes.

Fix some typos

---

CHANGELOG.md
src/source_analysis/mod.rs
src/source_analysis/tests.rs
tests/line_coverage.rs

Ignores all single line comments

---

README.md

Separate intro from other text, and improve readability.

readme: some improvements

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/source_analysis/items.rs
src/source_analysis/tests.rs

Ignore attributes on functions

---

src/args.rs

Add back the short `-v` flag

---

src/args.rs
src/config/types.rs

Fix default ValueEnum casing

---

Cargo.lock
Cargo.toml

Update coveralls to 0.6.0

---

src/report/coveralls.rs

Coveralls expect source path to have the Linux path separator. Otherwise, it cannot link them with the repository's source.
Fixes #1448

fix: coveralls report on windows

---

CHANGELOG.md
src/cargo.rs

Check if compiler is nightly and if so don't add rustup directive

---

CHANGELOG.md
src/cargo.rs
tests/mod.rs

Fixes #1499

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cargo.rs
src/config/mod.rs
src/config/types.rs
src/process_handling/ptrace_control.rs
src/report/coveralls.rs
src/report/json.rs
src/report/mod.rs
src/report/safe_json.rs
src/source_analysis/expressions.rs
src/source_analysis/items.rs
src/source_analysis/macros.rs
src/source_analysis/mod.rs
src/source_analysis/statements.rs
src/statemachine/instrumented.rs
src/statemachine/linux.rs
src/test_loader.rs
tests/mod.rs

Try out new profparser branch

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Prepare for release 0.28.0

---

CHANGELOG.md
src/cargo.rs

Attempt to fix toolchain woes in windows

---

CHANGELOG.md
src/report/json.rs

Adds in json summary

---

.github/workflows/rust.yml

Try to speedup CI

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
TROUBLESHOOTING.md

Initial work on troubleshooting guide

---

tests/mod.rs

Make sure rustflags not in test env

---

CHANGELOG.md
src/source_analysis/items.rs
src/source_analysis/tests.rs

Implement smarter generic detection

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Prepare release 0.29.0

---

Cargo.lock
Cargo.toml
tests/doc_coverage.rs
tests/failure_thresholds.rs
tests/failures.rs
tests/line_coverage.rs
tests/mod.rs
tests/test_types.rs
tests/workspaces.rs

Add in tracing-test

---

CHANGELOG.md
Cargo.lock
Cargo.toml

prepare for release again!

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Do release commit

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/config/mod.rs
src/statemachine/instrumented.rs

Apply object filtering on llvm profparsers

---

src/config/mod.rs
src/errors/mod.rs
src/lib.rs
src/statemachine/mod.rs
tests/mod.rs

FIll in some gaps in testing, refactor

---

CHANGELOG.md
src/lib.rs
src/report/cobertura.rs
src/report/lcov.rs
src/source_analysis/items.rs
src/source_analysis/mod.rs
src/source_analysis/tests.rs
src/test_loader.rs
src/traces.rs

Start revamping the function handling stuff

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Prepare for release

---

CHANGELOG.md
src/process_handling/linux.rs

A first fix from rustybug work

Fix aslr detection

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cargo.rs

Add the lib dir to the linker paths to try and fix procmacro crates

---

CHANGELOG.md
src/cargo.rs
tests/mod.rs

Disable dead code for mac

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/cargo.rs
src/statemachine/instrumented.rs
tests/mod.rs

Try to remove dead code from LLVM cov

---

src/cargo.rs
tests/data/doc_coverage/Cargo.toml

Ignore rs files in doctest directory

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/report/coveralls.rs
src/test_loader.rs

Trying some stuff to improve coveralls support

Add remote info to report type
